// <auto-generated />
namespace PeopleProTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelationbetweenDepoFaculty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationbetweenDepoFaculty));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011752364_Relation-between-Depo-Faculty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
